version: '3.4'

services:
  devcontainer:
    environment:
      - DISPLAY=:1
    volumes:
      - $${HOME}/.ssh:/home/devuser/.ssh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/1000/gdm/Xauthority:/home/devuser/.Xauthority:rw
