version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVUSER: devuser
    user: devuser
    volumes:
      - ..:/workspaces/lidarshooter