version: '3.4'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile-cuda
      args:
        DEVUSER: devuser
        DEVUID: 1000
        BUILDKIT_INLINE_CACHE: 0
    user: devuser
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_IP=${ROS_IP}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - QT_AUTO_SCREEN_SCALE_FACTOR=${QT_AUTO_SCREEN_SCALE_FACTOR}
    command: "sleep infinity"
    privileged: true
    volumes:
      - ..:/workspaces/lidarshooter
